[FIX][Vms]Bugs of vms
Jarsa/vehicle-maintenance-system pull request #49
Opened 2018-07-16 13:53 UTC by lmgr0312

This PR fixes different bugs: 

-The wrong path in some images of demo data
-The Tasks/Spare Parts when the preventive maintenances are triggered.
-The Create PO button in vms_order_line only appears when the order_line is an external part.
-The size of certains fonts in vms_kiosk_mode to prevent views with wrong design.

2018-07-16 13:54 UTC, lmgr0312 commented
@alan196 @ougc27 
Here we have some changes in the vms behavior... hope you have the chance to take a look around of this...

Regards!

2018-07-16 14:02 UTC, luistriana28 commented
👍

2018-07-16 14:06 UTC, ougc27 commented
Hello @lmgr0312 could you refactor this parameter please?

https://github.com/Jarsa-dev/vehicle-maintenance-system/blob/b75d76f3885261ecf42678b30cef75d5e72d22b3/vms/models/fleet_vehicle.py#L30-L31

Instead a system parameter could you create a field on a res.config.setting linked to the res.company please? :+1:

2018-07-16 14:11 UTC, alan196 requested changes

2018-07-16 14:11 UTC, alan196 commented on vms/models/vms_order_line.py
> +                lambda x: x.external_spare_parts) else False
`bool(rec.spare_part_ids.filtered(lambda x: x.external_spare_parts))`

2018-07-24 13:09 UTC, alan196 approved these changes

2018-07-24 13:09 UTC, merged